version: '3.8'

services:
  db-tickets:
    image: mysql:8.0
    container_name: mysql_tickets
    environment:
      MYSQL_ROOT_PASSWORD: root_password_segura
      MYSQL_DATABASE: sistematic_db
      MYSQL_USER: tics_user
      MYSQL_PASSWORD: tics_password
      TZ: America/Mexico_City
    ports:
      - "3307:3306"
    volumes:
      - tickets_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password_segura"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    # 🛡️ NUEVO: Conectamos la BD a la red externa
    networks:
      - sgc_default

  app-tickets:
    build: .
    container_name: app_tickets
    ports:
      - "4001:4001"
    environment:
      - DATABASE_URL=mysql://tics_user:tics_password@db-tickets:3306/sistematic_db
      - SESSION_SECRET=secreto-super-seguro-policia-morelia-2026
      - PORT=4001
      - TZ=America/Mexico_City
      - ALLOWED_ORIGINS=localhost:4001,10.1.0.160:4001
    depends_on:
      db-tickets:
        condition: service_healthy
    volumes:
      - tickets_archivos:/app/public/uploads
    restart: unless-stopped
    # 🛡️ NUEVO: Conectamos la App a la red externa
    networks:
      - sgc_default

volumes:
  tickets_mysql_data:
  tickets_archivos:

# 🛡️ NUEVO: Declaramos que la red sgc_default ya existe en el servidor
networks:
  sgc_default:
    external: true